[user]
name = "Cameron Wong"
email = "cam@camdar.io"

[ui]
diff-editor = "vimdirdiff"

[signing]
behavior = "own"
backend = "gpg"

[git]
sign-on-push = true

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@"]
tug- = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
